# Generated by Django 5.2.5 on 2025-11-03 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg', models.CharField(default='--', max_length=100)),
                ('spo2', models.FloatField(default=0)),
                ('nibp', models.CharField(default='--', max_length=50)),
                ('rr', models.FloatField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('status', models.CharField(default='Stable', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
