# Generated by Django 5.2.5 on 2025-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ambulancestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='AmbulanceStatus',
        ),
    ]
