# Generated by Django 5.2.5 on 2025-11-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_ambulancestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancestatus',
            name='last_update',
        ),
        migrations.AddField(
            model_name='ambulancestatus',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
